---
title: "fivbviz"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    # vertical_layout: fill or scroll
    theme: 
      version: 4
---

```{r setup, include=FALSE}
library(dplyr)
library(reactable)
library(fivbvis)
library(flexdashboard)
library(shiny)
v_caching(FALSE)
Sys.setlocale(category = 'LC_ALL', locale = 'English_United States.1252')
Y <- format(Sys.Date(), "%Y")

pl <- list(Fields = "No Season ShortNameOrName StartDate EndDate Gender OrganizerType Status")
tournaments <- v_get_volley_tournament_list(parent = pl) %>% arrange(desc(startDate))

df.colDef <- colDef(
        header = function(value) {
            fivbvis:::first_to_upper(value)
        },
        headerVAlign = 'bottom',
        minWidth = 70
    )

tl.colDef <- list(
    no = colDef(minWidth = 50, filterable = FALSE, align = "left"),
    season = colDef(minWidth = 50),
    shortNameOrName = colDef(name = "Tournament", minWidth = 240)
)

```
```{r server, include=FALSE}
output$tours <- renderReactable({
    reactable(
    tournaments,
    columns = tl.colDef,
    defaultColDef = df.colDef,
    defaultPageSize = 20,
    resizable = TRUE,
    filterable = TRUE,
    highlight = TRUE,
    striped = TRUE,
    compact = TRUE,
    wrap = FALSE,
    selection = "single",
    onClick = "select",
    rowStyle = JS("function(rowInfo) {
        if (rowInfo && rowInfo.selected) {
            return { backgroundColor: '#d4d4d4', boxShadow: 'inset 2px 0 0 0 #ffa62d' }
        }
    }")
    )
})

state <- reactive(getReactableState("tours", "selected"))
output$table_state <- renderPrint({
    state()
  })
```


Tournament
=====================================  

Inputs {.sidebar}
-------------------------------------

```{r}
# change season
verbatimTextOutput("table_state")
# selectizeInput('sel_season', 'Season', choices = c(Y:1949), selected = Y)
```
    
Column {data-width=1000}
-------------------------------------
    
### tournament list
    
```{r}
reactableOutput("tours")
```
