---
title: "`r params$marktext`"
author: '`r fontawesome::fa(name = "user")` wehsLai'
date: '`r fontawesome::fa(name = "calendar-day")` `r format(Sys.time(), "%Y-%m-%d %H:%M %Z")`'
output: 
    html_document:
      includes:
        after_body: footer.html  
      theme:
        version: 5
        base_font:
          google: "Source Sans Pro"
      toc: true
      toc_depth: 3
      toc_float:
        collapsed: false
        smooth_scroll: false
params: 
    ds: NULL
    marktext: NULL
    showAll: FALSE
    number: 20
---

<style type="text/css">
div.main-container {  
  max-width: 1600px; 
}

h1.title {
  font-size: 2.25rem;
}

h4.author, h4.date {
  font-size: 1.25rem;
}
</style>

```{r setup, include=FALSE}
ds <- params$ds
marktext <- params$marktext
showAll <- params$showAll
number <- params$number
```

## [P5] Players ranking by skills

### Score

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
type <- "c"
isTeam <- FALSE
# data
f <- rankBySkillDf(ds$statistics$player_agg, type, isTeam, showAll = showAll, number= number)
# render
rankBySkillshow(f, type, isTeam) %>% gtstyle(type, isTeam, subtitle = params$marktext)
```

<br>

### Attack

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
type <- "a"
isTeam <- FALSE
# data
f <- rankBySkillDf(ds$statistics$player_agg, type, isTeam, showAll = showAll, number= number)
# render
rankBySkillshow(f, type, isTeam) %>% gtstyle(type, isTeam, subtitle = params$marktext)
```

<br>

### Block

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
type <- "b"
isTeam <- FALSE
# data
f <- rankBySkillDf(ds$statistics$player_agg, type, isTeam, showAll = showAll, number= number)
# render
rankBySkillshow(f, type, isTeam) %>% gtstyle(type, isTeam, subtitle = params$marktext)
```

<br>

### Serve

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
type <- "s"
isTeam <- FALSE
# data
f <- rankBySkillDf(ds$statistics$player_agg, type, isTeam, showAll = showAll, number= number)
# render
rankBySkillshow(f, type, isTeam) %>% gtstyle(type, isTeam, subtitle = params$marktext)
```

<br>

### Dig

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
type <- "d"
isTeam <- FALSE
# data
f <- rankBySkillDf(ds$statistics$player_agg, type, isTeam, showAll = showAll, number= number)
# render
rankBySkillshow(f, type, isTeam) %>% gtstyle(type, isTeam, subtitle = params$marktext)
```

<br>

### Set

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
type <- "e"
isTeam <- FALSE
# data
f <- rankBySkillDf(ds$statistics$player_agg, type, isTeam, showAll = showAll, number= number)
# render
rankBySkillshow(f, type, isTeam) %>% gtstyle(type, isTeam, subtitle = params$marktext)
```

<br>

### Receive

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
type <- "r"
isTeam <- FALSE
# data
f <- rankBySkillDf(ds$statistics$player_agg, type, isTeam, showAll = showAll, number= number)
# render
rankBySkillshow(f, type, isTeam) %>% gtstyle(type, isTeam, subtitle = params$marktext)
```

<br>

### Liberos

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
type <- "l"
isTeam <- FALSE
# data
f <- rankBySkillDf(ds$statistics$player_agg, type, isTeam, showAll = showAll, number= number)
# render
rankBySkillshow(f, type, isTeam) %>% gtstyle(type, isTeam, subtitle = params$marktext)
```

\newpage
## [P6] Teams ranking by skills

### Score

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
type <- "c"
isTeam <- TRUE
# data
f <- rankBySkillDf(ds$statistics$team_agg, type, isTeam, showAll = showAll, number= number)
# render
rankBySkillshow(f, type, isTeam) %>% gtstyle(type, isTeam, subtitle = params$marktext)
```

<br>

### Attack

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
type <- "a"
isTeam <- TRUE
# data
f <- rankBySkillDf(ds$statistics$team_agg, type, isTeam, showAll = showAll, number= number)
# render
rankBySkillshow(f, type, isTeam) %>% gtstyle(type, isTeam, subtitle = params$marktext)
```

<br>

### Block

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
type <- "b"
isTeam <- TRUE
# data
f <- rankBySkillDf(ds$statistics$team_agg, type, isTeam, showAll = showAll, number= number)
# render
rankBySkillshow(f, type, isTeam) %>% gtstyle(type, isTeam, subtitle = params$marktext)
```

<br>

### Serve

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
type <- "s"
isTeam <- TRUE
# data
f <- rankBySkillDf(ds$statistics$team_agg, type, isTeam, showAll = showAll, number= number)
# render
rankBySkillshow(f, type, isTeam) %>% gtstyle(type, isTeam, subtitle = params$marktext)
```

<br>

### Dig

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
type <- "d"
isTeam <- TRUE
# data
f <- rankBySkillDf(ds$statistics$team_agg, type, isTeam, showAll = showAll, number= number)
# render
rankBySkillshow(f, type, isTeam) %>% gtstyle(type, isTeam, subtitle = params$marktext)
```

<br>

### Set

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
type <- "e"
isTeam <- TRUE
# data
f <- rankBySkillDf(ds$statistics$team_agg, type, isTeam, showAll = showAll, number= number)
# render
rankBySkillshow(f, type, isTeam) %>% gtstyle(type, isTeam, subtitle = params$marktext)
```

<br>

### Receive

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
type <- "r"
isTeam <- TRUE
# data
f <- rankBySkillDf(ds$statistics$team_agg, type, isTeam, showAll = showAll, number= number)
# render
rankBySkillshow(f, type, isTeam) %>% gtstyle(type, isTeam, subtitle = params$marktext)
```

<br>

### Team Errors

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
type <- "f"
isTeam <- TRUE
# data
f <- rankBySkillDf(ds$statistics$team_agg, type, isTeam, showAll = showAll, number= number)
# render
rankBySkillshow(f, type, isTeam) %>% gtstyle(type, isTeam, subtitle = params$marktext)
```

<br>
