---
title: "`r params$marktext`"
author: "wehsLai"
url: "https://github.com/wehsLai/fivbviz"
date: "`r Sys.Date()`"
output: 
    html_document:
      theme:
        version: 4
        base_font:
          google: "Source Sans Pro"
        code_font:
          google: "Fira Code"
      toc: true
      toc_depth: 2
      toc_float:
        collapsed: false
      fig_width: 8
      fig_height: 6.5        
params: 
    ds: NULL
    marktext: NULL
---

<style type="text/css">
div.main-container {  max-width: 1600px; }
</style>

```{r setup, include=FALSE}
showSeason <- TRUE
ds <- params$ds
marktext <- params$marktext
```

## Player Charts {.tabset}

### Best Scorers

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
id <- "scorer"
ns <- NS(id)
type <- "c"
isTeam <- FALSE
# data
f <- rankBySkillDf(ds$statistics$player_agg, type, isTeam)
# render
renPlotly(id, f, type, marktext, isTeam)
tagList(
  fluidRow(
    column(width = 9, align = "left", renTitle(type)),
    column(width = 2, align = "right", renLimit(type)),
    column(width = 1, align = "right", tags$button("CSV", onclick = sprintf("Reactable.downloadDataCSV('%s')", ns("table"))))
  ),
  renTable(id, f, type, isTeam)
)
```

### Best Attackers

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
id <- "attacker"
ns <- NS(id)
type <- "a"
isTeam <- FALSE
# data
f <- rankBySkillDf(ds$statistics$player_agg, type, isTeam)
# render
renPlotly(id, f, type, marktext, isTeam)
tagList(
  fluidRow(
    column(width = 9, align = "left", renTitle(type)),
    column(width = 2, align = "right", renLimit(type)),
    column(width = 1, align = "right", tags$button("CSV", onclick = sprintf("Reactable.downloadDataCSV('%s')", ns("table"))))
  ),
  renTable(id, f, type, isTeam)
)
```

### Best Blockers

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
id <- "blocker"
ns <- NS(id)
type <- "b"
isTeam <- FALSE
# data
f <- rankBySkillDf(ds$statistics$player_agg, type, isTeam)
# render
renPlotly(id, f, type, marktext, isTeam)
tagList(
  fluidRow(
    column(width = 9, align = "left", renTitle(type)),
    column(width = 2, align = "right", renLimit(type)),
    column(width = 1, align = "right", tags$button("CSV", onclick = sprintf("Reactable.downloadDataCSV('%s')", ns("table"))))
  ),
  renTable(id, f, type, isTeam)
)
```

### Best Servers

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
id <- "server"
ns <- NS(id)
type <- "s"
isTeam <- FALSE
# data
f <- rankBySkillDf(ds$statistics$player_agg, type, isTeam)
# render
renPlotly(id, f, type, marktext, isTeam)
tagList(
  fluidRow(
    column(width = 9, align = "left", renTitle(type)),
    column(width = 2, align = "right", renLimit(type)),
    column(width = 1, align = "right", tags$button("CSV", onclick = sprintf("Reactable.downloadDataCSV('%s')", ns("table"))))
  ),
  renTable(id, f, type, isTeam)
)
```

### Best Diggers

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
id <- "digger"
ns <- NS(id)
type <- "d"
isTeam <- FALSE
# data
f <- rankBySkillDf(ds$statistics$player_agg, type, isTeam)
# render
renPlotly(id, f, type, marktext, isTeam)
tagList(
  fluidRow(
    column(width = 9, align = "left", renTitle(type)),
    column(width = 2, align = "right", renLimit(type)),
    column(width = 1, align = "right", tags$button("CSV", onclick = sprintf("Reactable.downloadDataCSV('%s')", ns("table"))))
  ),
  renTable(id, f, type, isTeam)
)
```

### Best Setters

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
id <- "setter"
ns <- NS(id)
type <- "e"
isTeam <- FALSE
# data
f <- rankBySkillDf(ds$statistics$player_agg, type, isTeam)
# render
renPlotly(id, f, type, marktext, isTeam)
tagList(
  fluidRow(
    column(width = 9, align = "left", renTitle(type)),
    column(width = 2, align = "right", renLimit(type)),
    column(width = 1, align = "right", tags$button("CSV", onclick = sprintf("Reactable.downloadDataCSV('%s')", ns("table"))))
  ),
  renTable(id, f, type, isTeam)
)
```

### Best Receivers

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
id <- "receiver"
ns <- NS(id)
type <- "r"
isTeam <- FALSE
# data
f <- rankBySkillDf(ds$statistics$player_agg, type, isTeam)
# render
renPlotly(id, f, type, marktext, isTeam)
tagList(
  fluidRow(
    column(width = 9, align = "left", renTitle(type)),
    column(width = 2, align = "right", renLimit(type)),
    column(width = 1, align = "right", tags$button("CSV", onclick = sprintf("Reactable.downloadDataCSV('%s')", ns("table"))))
  ),
  renTable(id, f, type, isTeam)
)
```

### Best Liberos

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
id <- "libero"
ns <- NS(id)
type <- "l"
isTeam <- FALSE
# data
f <- rankBySkillDf(ds$statistics$player_agg, type, isTeam)
# render
renPlotly(id, f, type, marktext, isTeam)
tagList(
  fluidRow(
    column(width = 9, align = "left", renTitle(type)),
    column(width = 2, align = "right", renLimit(type)),
    column(width = 1, align = "right", tags$button("CSV", onclick = sprintf("Reactable.downloadDataCSV('%s')", ns("table"))))
  ),
  renTable(id, f, type, isTeam)
)
```

## Team Charts {.tabset}

### Best Scorers

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
id <- "scorer-team"
ns <- NS(id)
type <- "c"
isTeam <- TRUE
# data
f <- rankBySkillDf(ds$statistics$team_agg, type, isTeam)
# render
renPlotly(id, f, type, marktext, isTeam)
tagList(
  fluidRow(
    column(width = 9, align = "left", renTitle(type)),
    column(width = 2, align = "right", renLimit(type)),
    column(width = 1, align = "right", tags$button("CSV", onclick = sprintf("Reactable.downloadDataCSV('%s')", ns("table"))))
  ),
  renTable(id, f, type, isTeam)
)
```

### Best Attackers

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
id <- "attacker-team"
ns <- NS(id)
type <- "a"
isTeam <- TRUE
# data
f <- rankBySkillDf(ds$statistics$team_agg, type, isTeam)
# render
renPlotly(id, f, type, marktext, isTeam)
tagList(
  fluidRow(
    column(width = 9, align = "left", renTitle(type)),
    column(width = 2, align = "right", renLimit(type)),
    column(width = 1, align = "right", tags$button("CSV", onclick = sprintf("Reactable.downloadDataCSV('%s')", ns("table"))))
  ),
  renTable(id, f, type, isTeam)
)
```

### Best Blockers

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
id <- "blocker-team"
ns <- NS(id)
type <- "b"
isTeam <- TRUE
# data
f <- rankBySkillDf(ds$statistics$team_agg, type, isTeam)
# render
renPlotly(id, f, type, marktext, isTeam)
tagList(
  fluidRow(
    column(width = 9, align = "left", renTitle(type)),
    column(width = 2, align = "right", renLimit(type)),
    column(width = 1, align = "right", tags$button("CSV", onclick = sprintf("Reactable.downloadDataCSV('%s')", ns("table"))))
  ),
  renTable(id, f, type, isTeam)
)
```

### Best Servers

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
id <- "server-team"
ns <- NS(id)
type <- "s"
isTeam <- TRUE
# data
f <- rankBySkillDf(ds$statistics$team_agg, type, isTeam)
# render
renPlotly(id, f, type, marktext, isTeam)
tagList(
  fluidRow(
    column(width = 9, align = "left", renTitle(type)),
    column(width = 2, align = "right", renLimit(type)),
    column(width = 1, align = "right", tags$button("CSV", onclick = sprintf("Reactable.downloadDataCSV('%s')", ns("table"))))
  ),
  renTable(id, f, type, isTeam)
)
```

### Best Diggers

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
id <- "digger-team"
ns <- NS(id)
type <- "d"
isTeam <- TRUE
# data
f <- rankBySkillDf(ds$statistics$team_agg, type, isTeam)
# render
renPlotly(id, f, type, marktext, isTeam)
tagList(
  fluidRow(
    column(width = 9, align = "left", renTitle(type)),
    column(width = 2, align = "right", renLimit(type)),
    column(width = 1, align = "right", tags$button("CSV", onclick = sprintf("Reactable.downloadDataCSV('%s')", ns("table"))))
  ),
  renTable(id, f, type, isTeam)
)
```

### Best Setters

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
id <- "setter-team"
ns <- NS(id)
type <- "e"
isTeam <- TRUE
# data
f <- rankBySkillDf(ds$statistics$team_agg, type, isTeam)
# render
renPlotly(id, f, type, marktext, isTeam)
tagList(
  fluidRow(
    column(width = 9, align = "left", renTitle(type)),
    column(width = 2, align = "right", renLimit(type)),
    column(width = 1, align = "right", tags$button("CSV", onclick = sprintf("Reactable.downloadDataCSV('%s')", ns("table"))))
  ),
  renTable(id, f, type, isTeam)
)
```

### Best Receivers

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
id <- "receiver-team"
ns <- NS(id)
type <- "r"
isTeam <- TRUE
# data
f <- rankBySkillDf(ds$statistics$team_agg, type, isTeam)
# render
renPlotly(id, f, type, marktext, isTeam)
tagList(
  fluidRow(
    column(width = 9, align = "left", renTitle(type)),
    column(width = 2, align = "right", renLimit(type)),
    column(width = 1, align = "right", tags$button("CSV", onclick = sprintf("Reactable.downloadDataCSV('%s')", ns("table"))))
  ),
  renTable(id, f, type, isTeam)
)
```

### Team Errors

```{r echo=FALSE, message=FALSE, warning=FALSE}
# parameters
id <- "error-team"
ns <- NS(id)
type <- "f"
isTeam <- TRUE
# data
f <- rankBySkillDf(ds$statistics$team_agg, type, isTeam)
# render
renPlotly(id, f, type, marktext, isTeam)
tagList(
  fluidRow(
    column(width = 9, align = "left", renTitle(type)),
    column(width = 2, align = "right", renLimit(type)),
    column(width = 1, align = "right", tags$button("CSV", onclick = sprintf("Reactable.downloadDataCSV('%s')", ns("table"))))
  ),
  renTable(id, f, type, isTeam)
)
```
